version: "3.1"

services:
  mongo:
    build:
      context: ./docker
      dockerfile: Dockerfile.mongodb
    networks:
      - readit_network
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    # ports:
    #   - "80:3000"
    #   - "5000:5000"
    environment:
      # env for backend
      - NODE_ENV=production
      - MONGODB_URL=mongodb://mongo:27017/readit
      - APP_URL=http://localhost
      - FRONT_END_URL=http://localhost
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DEFAULT_GOOGLE_PASSWORD=${DEFAULT_GOOGLE_PASSWORD}
    restart: always
    depends_on:
      - mongo
    networks:
      - readit_network
    links:
      - "mongo:db_server" # Alias mongo as db_server
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mongo
      - app
    networks:
      - readit_network

networks:
  readit_network:
